package com.example.mustag.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFFBB48FB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBAF295)
val md_theme_light_onPrimaryContainer = Color(0xFF092100)
val md_theme_light_secondary = Color(0xFF56624B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E7CA)
val md_theme_light_onSecondaryContainer = Color(0xFF141E0D)
val md_theme_light_tertiary = Color(0xFF386666)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBBEBEB)
val md_theme_light_onTertiaryContainer = Color(0xFF002020)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFDF5)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFDFDF5)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF43483E)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
val md_theme_light_inverseSurface = Color(0xFF2F312C)
val md_theme_light_inversePrimary = Color(0xFF9FD67C)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF3A6A1D)
val md_theme_light_outlineVariant = Color(0xFFC4C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF5F17DF)
val md_theme_dark_onPrimary = Color(0xFF000238)
val md_theme_dark_primaryContainer = Color(0xFF0E0451)
val md_theme_dark_onPrimaryContainer = Color(0xFFB995F2)
val md_theme_dark_secondary = Color(0xFFB772FB)
val md_theme_dark_onSecondary = Color(0xFF171718)
val md_theme_dark_secondaryContainer = Color(0xFF0C0037)
val md_theme_dark_onSecondaryContainer = Color(0xFFDACAE7)
val md_theme_dark_tertiary = Color(0xFFA3A0CF)
val md_theme_dark_onTertiary = Color(0xFF0C0037)
val md_theme_dark_tertiaryContainer = Color(0xFF131124)
val md_theme_dark_onTertiaryContainer = Color(0xFFD3BBEB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0D0D0D)
val md_theme_dark_onBackground = Color(0xFFD4D4D4)
val md_theme_dark_surface = Color(0xFF19181C)
val md_theme_dark_onSurface = Color(0xFFE3E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF3F3E48)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BB)
val md_theme_dark_outline = Color(0xFF8C8692)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE0DCE3)
val md_theme_dark_inversePrimary = Color(0xFF1E1031)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9C7CD6)
val md_theme_dark_outlineVariant = Color(0xFF403E48)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF243B16)